/*
 * puddle.farm API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DistributionEntry {
    /// Distribution data by floor
    #[serde(rename = "distribution_floor", skip_serializing_if = "Option::is_none")]
    pub distribution_floor: Option<Vec<Vec<i64>>>,
    /// Number of players in the last month
    #[serde(rename = "one_month_players", skip_serializing_if = "Option::is_none")]
    pub one_month_players: Option<i64>,
    /// Rating distribution results
    #[serde(rename = "distribution_rating", skip_serializing_if = "Option::is_none")]
    pub distribution_rating: Option<Vec<serde_json::Value>>,
}

impl DistributionEntry {
    pub fn new() -> DistributionEntry {
        DistributionEntry {
            distribution_floor: None,
            one_month_players: None,
            distribution_rating: None,
        }
    }
}

