/*
 * puddle.farm API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MatchupCharResponse {
    #[serde(rename = "char_name", skip_serializing_if = "Option::is_none")]
    pub char_name: Option<String>,
    #[serde(rename = "char_short", skip_serializing_if = "Option::is_none")]
    pub char_short: Option<String>,
    #[serde(rename = "matchups", skip_serializing_if = "Option::is_none")]
    pub matchups: Option<Vec<models::MatchupEntry>>,
}

impl MatchupCharResponse {
    pub fn new() -> MatchupCharResponse {
        MatchupCharResponse {
            char_name: None,
            char_short: None,
            matchups: None,
        }
    }
}

