/*
 * puddle.farm API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MatchupResponse {
    #[serde(rename = "last_update", skip_serializing_if = "Option::is_none")]
    pub last_update: Option<String>,
    #[serde(rename = "data_all", skip_serializing_if = "Option::is_none")]
    pub data_all: Option<Vec<models::MatchupCharResponse>>,
    #[serde(rename = "data_1700", skip_serializing_if = "Option::is_none")]
    pub data_1700: Option<Vec<models::MatchupCharResponse>>,
}

impl MatchupResponse {
    pub fn new() -> MatchupResponse {
        MatchupResponse {
            last_update: None,
            data_all: None,
            data_1700: None,
        }
    }
}

