/*
 * puddle.farm API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MatchupEntry {
    #[serde(rename = "char_name", skip_serializing_if = "Option::is_none")]
    pub char_name: Option<String>,
    #[serde(rename = "char_short", skip_serializing_if = "Option::is_none")]
    pub char_short: Option<String>,
    #[serde(rename = "wins", skip_serializing_if = "Option::is_none")]
    pub wins: Option<i64>,
    #[serde(rename = "total_games", skip_serializing_if = "Option::is_none")]
    pub total_games: Option<i64>,
}

impl MatchupEntry {
    pub fn new() -> MatchupEntry {
        MatchupEntry {
            char_name: None,
            char_short: None,
            wins: None,
            total_games: None,
        }
    }
}

