/*
 * puddle.farm API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RankResponse {
    /// List of player rankings
    #[serde(rename = "ranks", skip_serializing_if = "Option::is_none")]
    pub ranks: Option<Vec<models::PlayerRankResponse>>,
}

impl RankResponse {
    pub fn new() -> RankResponse {
        RankResponse {
            ranks: None,
        }
    }
}

