/*
 * puddle.farm API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatsResponse {
    /// Timestamp of the last update
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<String>,
    /// Total number of games played
    #[serde(rename = "total_games", skip_serializing_if = "Option::is_none")]
    pub total_games: Option<i64>,
    /// Number of games played in the last month
    #[serde(rename = "one_month_games", skip_serializing_if = "Option::is_none")]
    pub one_month_games: Option<i64>,
    /// Number of games played in the last week
    #[serde(rename = "one_week_games", skip_serializing_if = "Option::is_none")]
    pub one_week_games: Option<i64>,
    /// Number of games played in the last day
    #[serde(rename = "one_day_games", skip_serializing_if = "Option::is_none")]
    pub one_day_games: Option<i64>,
    /// Number of games played in the last hour
    #[serde(rename = "one_hour_games", skip_serializing_if = "Option::is_none")]
    pub one_hour_games: Option<i64>,
    /// Total number of players
    #[serde(rename = "total_players", skip_serializing_if = "Option::is_none")]
    pub total_players: Option<i64>,
    /// Number of players in the last month
    #[serde(rename = "one_month_players", skip_serializing_if = "Option::is_none")]
    pub one_month_players: Option<i64>,
    /// Number of players in the last week
    #[serde(rename = "one_week_players", skip_serializing_if = "Option::is_none")]
    pub one_week_players: Option<i64>,
    /// Number of players in the last day
    #[serde(rename = "one_day_players", skip_serializing_if = "Option::is_none")]
    pub one_day_players: Option<i64>,
    /// Number of players in the last hour
    #[serde(rename = "one_hour_players", skip_serializing_if = "Option::is_none")]
    pub one_hour_players: Option<i64>,
}

impl StatsResponse {
    pub fn new() -> StatsResponse {
        StatsResponse {
            timestamp: None,
            total_games: None,
            one_month_games: None,
            one_week_games: None,
            one_day_games: None,
            one_hour_games: None,
            total_players: None,
            one_month_players: None,
            one_week_players: None,
            one_day_players: None,
            one_hour_players: None,
        }
    }
}

