/*
 * puddle.farm API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TopRating {
    /// Timestamp when this rating was achieved
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<String>,
    /// The top rating value achieved
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<f32>,
    /// Rating deviation at the time of top rating
    #[serde(rename = "deviation", skip_serializing_if = "Option::is_none")]
    pub deviation: Option<f32>,
}

impl TopRating {
    pub fn new() -> TopRating {
        TopRating {
            timestamp: None,
            value: None,
            deviation: None,
        }
    }
}

